Bob: Started to introduce fields apar, bpar. An (apparently) unrelated issue is preventing us from making: mpif90  -ffree-line-length-none -fno-backslash -fdefault-real-8 -fdefault-double-8  -O3 -I. -Iutils -Igeo/vmec_interface/mini_libstell -Igeo/vmec_interface -Igeo -I..     -I/usr/include     -c geo/vmec_interface/vmec_to_stella_geometry_interface.f90 geo/vmec_interface/vmec_to_stella_geometry_interface.f90:43:8:
     use read_wout_mod, only: read_wout_file, read_wout_deallocate
        1
Fatal Error: Can't open module file ‘read_wout_mod.mod’ for reading at (1): No such file or directory